version: 2

updates:
  - package-ecosystem: npm
    reviewers:
      - jradtilbrook
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
    pull-request-branch-name:
      separator: '-'
